
Options = -Xlint

wordmap/Position.class : wordmap/Position.java
	javac $(Options) wordmap/Position.java

wordmap/Occurrences.class : wordmap/Occurrences.java
	javac $(Options) wordmap/Occurrences.java

wordmap/Syntax.class : wordmap/Syntax.java
	javac $(Options) wordmap/Syntax.java

wordmap/Builder.class : wordmap/Builder.java
	javac $(Options) wordmap/Builder.java

Tester.class : Tester.java
	javac $(Options) Tester.java


